//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSMViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YSMViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Animations 的本地化字符串。
        /// </summary>
        public static string Animations {
            get {
                return ResourceManager.GetString("Animations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bones 的本地化字符串。
        /// </summary>
        public static string Bones {
            get {
                return ResourceManager.GetString("Bones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse All 的本地化字符串。
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complexity 的本地化字符串。
        /// </summary>
        public static string ComplexityCol {
            get {
                return ResourceManager.GetString("ComplexityCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Components 的本地化字符串。
        /// </summary>
        public static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dismiss 的本地化字符串。
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop to open 的本地化字符串。
        /// </summary>
        public static string DropHint {
            get {
                return ResourceManager.GetString("DropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .ysm file 的本地化字符串。
        /// </summary>
        public static string DropHintExt {
            get {
                return ResourceManager.GetString("DropHintExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a folder to browse YSM models 的本地化字符串。
        /// </summary>
        public static string EmptyFolder {
            get {
                return ResourceManager.GetString("EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a .ysm file or drag and drop here 的本地化字符串。
        /// </summary>
        public static string EmptyState {
            get {
                return ResourceManager.GetString("EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand All 的本地化字符串。
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Front view 的本地化字符串。
        /// </summary>
        public static string FrontView {
            get {
                return ResourceManager.GetString("FrontView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide All 的本地化字符串。
        /// </summary>
        public static string HideAll {
            get {
                return ResourceManager.GetString("HideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left view 的本地化字符串。
        /// </summary>
        public static string LeftView {
            get {
                return ResourceManager.GetString("LeftView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Folder 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready. Open a .ysm file to begin. 的本地化字符串。
        /// </summary>
        public static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search... 的本地化字符串。
        /// </summary>
        public static string SearchPrompt {
            get {
                return ResourceManager.GetString("SearchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show All 的本地化字符串。
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop and reset animation 的本地化字符串。
        /// </summary>
        public static string StopAnim {
            get {
                return ResourceManager.GetString("StopAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch language 的本地化字符串。
        /// </summary>
        public static string SwitchLanguage {
            get {
                return ResourceManager.GetString("SwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textures 的本地化字符串。
        /// </summary>
        public static string Textures {
            get {
                return ResourceManager.GetString("Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle theme 的本地化字符串。
        /// </summary>
        public static string ToggleTheme {
            get {
                return ResourceManager.GetString("ToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top view 的本地化字符串。
        /// </summary>
        public static string TopView {
            get {
                return ResourceManager.GetString("TopView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View on GitHub 的本地化字符串。
        /// </summary>
        public static string ViewOnGitHub {
            get {
                return ResourceManager.GetString("ViewOnGitHub", resourceCulture);
            }
        }
    }
}
